services:
  - type: web
    name: muskan-portfolio
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: muskan-portfolio-db
          property: connectionString
    autoDeploy: false

databases:
  - name: muskan-portfolio-db
    databaseName: portfolio
    user: portfolio_user